name: Deploy hexo blog

on:
  push:
    branches:
    - post

env:
  POST_PATH: Hexo-Blog/Post

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with: 
          ref: 'main'

      - name: Initiallize
        run: |
          sudo apt update
          sudo apt upgrade -y
          mkdir -p $POST_PATH

      - name: Sync Post
        uses: actions/checkout@v4
        with: 
          ref: 'post'
          path: $POST_PATH

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          GITHUBDEPLOY: ${{ secrets.GITHUBDEPLOY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$GITHUBDEPLOY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "HualiMoa-AQ"
          git config --global user.email "hualimao_aq@163.com"

      - name: Set Domain
        env:
          DOMAIN: ${{ vars.DOMAIN }}
        run:
          echo $DOMAIN >> source/CNAME

      - name: Install dependencies
        run: |
          sudo apt install nasm
          npm i -g hexo-cli
          npm ci

      - name: Add Post
        run: |
          ls $POST_PATH | grep -e "md" | awk '/.md/ {gsub(".md",""); print $1}' >> $POST_PATH/post_list.txt
          while read post
          do
            hexo new post $post
            cp -f $POST_PATH/$post.md source/_posts
          done < $POST_PATH/post_list.txt

      - name: Deploy hexo
        run: |
          hexo clean
          hexo d -g